# Generated by Django 4.1.7 on 2023-06-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_schedule_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='artist',
        ),
        migrations.AddField(
            model_name='booking',
            name='artist_email',
            field=models.EmailField(default='john@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='artist_name',
            field=models.CharField(default='John Doe', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='artist_phone_number',
            field=models.CharField(default='1234567890', max_length=15),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
